// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEk_qpV6oeJYJPirJp1BDLr9KEKPY7aQM',
    appId: '1:63794640710:web:e375d6b6e50d9424701747',
    messagingSenderId: '63794640710',
    projectId: 'auth-f1950',
    authDomain: 'auth-f1950.firebaseapp.com',
    storageBucket: 'auth-f1950.appspot.com',
    measurementId: 'G-CEJ5V09DZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4E3eKdujDolsOoM8Wp3hRoLUkb7-3Fg',
    appId: '1:63794640710:android:9f25fdb5f72f0fe4701747',
    messagingSenderId: '63794640710',
    projectId: 'auth-f1950',
    storageBucket: 'auth-f1950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ15cM3C3qEGDweLEb7URvrlNaN2HxpNw',
    appId: '1:63794640710:ios:1b7a8e19ec501e2a701747',
    messagingSenderId: '63794640710',
    projectId: 'auth-f1950',
    storageBucket: 'auth-f1950.appspot.com',
    iosClientId: '63794640710-t6fnbt1tatannun8b2lptpqkgikqs7s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ15cM3C3qEGDweLEb7URvrlNaN2HxpNw',
    appId: '1:63794640710:ios:1b7a8e19ec501e2a701747',
    messagingSenderId: '63794640710',
    projectId: 'auth-f1950',
    storageBucket: 'auth-f1950.appspot.com',
    iosClientId: '63794640710-t6fnbt1tatannun8b2lptpqkgikqs7s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth',
  );
}
